name: CD - DN SMOKE BAR

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Installing dependencies
        run: npm ci

      - name: Building
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --global user.email "digaodev46@gmail.com"
          git config --global user.name "Digao46"
          git config credential.helper store
          git push --set-url origin https://$GH_TOKEN@github.com/Digao46/dn-smoke-bar.git
          git push --set-upstream origin main
          npm run deploy

      # - name: Deploy to gh-pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      #     publish_dir: ./build
