name: CD - DMANAGER APP

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setting-up git
        run: |
          git config --global user.email "digaodev46@gmail.com"
          git config --global user.name "Diogo Melo"
          git config --global credential.helper store

      - name: Using PAT to authenticate
        run: git remote set-url origin https://Digao46:${{ secrets.GITHUB_TOKEN }}@github.com/Digao46/dn-smoke-bar.git

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Installing dependencies
        run: npm ci

      - name: Building
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        run: npm run build

      - name: Deploy to GitHub Pages
        run: npm run deploy
